
GET http://localhost:4000/

###
GET http://localhost:4000/listadoOpinion

###
POST http://localhost:4000/registrar 
Content-Type: application/json

{
"comentario":"mal", "nc":2
}

###
GET http://localhost:4000/uno/615e00c4d992625ca2322507
